export enum ActionTypes {
  GET_CONCEPTS_REQUEST = 'GET_CONCEPTS_REQUEST',
  GET_CONCEPTS_SUCCESS = 'GET_CONCEPTS_SUCCESS',
  GET_CONCEPTS_FAILURE = 'GET_CONCEPTS_FAILURE',

  CREATE_CONCEPT_REQUEST = 'CREATE_CONCEPT_REQUEST',
  CREATE_CONCEPT_SUCCESS = 'CREATE_CONCEPT_SUCCESS',
  CREATE_CONCEPT_FAILURE = 'CREATE_CONCEPT_FAILURE',

  UPDATE_CONCEPT_REQUEST = 'UPDATE_CONCEPT_REQUEST',
  UPDATE_CONCEPT_SUCCESS = 'UPDATE_CONCEPT_SUCCESS',
  UPDATE_CONCEPT_FAILURE = 'UPDATE_CONCEPT_FAILURE',

  DELETE_CONCEPT_REQUEST = 'DELETE_CONCEPT_REQUEST',
  DELETE_CONCEPT_SUCCESS = 'DELETE_CONCEPT_SUCCESS',
  DELETE_CONCEPT_FAILURE = 'DELETE_CONCEPT_FAILURE',

  SET_USER_INFO = 'SET_USER_INFO',

  SEND_FILE_REQUEST = 'SEND_FILE_REQUEST',
  SEND_FILE_SUCCESS = 'SEND_FILE_SUCCESS',
  SEND_FILE_FAILURE = 'SEND_FILE_FAILURE',
}
